### PR TITLE
fix broken link

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by 161chihuahuas** [comment]
Woops! Thanks, will republish the docs site!

**Comment by ralphtheninja** [comment]
Docs site works but not the .md link in the readme. Do you have automatic .html conversion or something?

**Comment by 161chihuahuas** [comment]
Yeah the site is generated with JSDoc, so it's a little clunky to get links to work right both on github and on the site. Is something still broken?

**Comment by ralphtheninja** [comment]
Nope. All good!

**Pull request merged**
