### PR TITLE
Block stream improvement

### PR DESCRIPTION
**Pull request by vasilenkoalexey**
I added a test for the transformation function, and also optimized: the concatenation was replaced by the queue of incoming data blocks, which minimizes copy operations and memory usage.

### CODE REVIEW

**Comment by braydonf** [comment]
Neat, any performance boost?

**Comment by vasilenkoalexey** [comment]
Perfomance depends on input and output block size. I use simple bench
```
const BlockStream = require('./block-stream');
var bs = new BlockStream(BlockStream.DEFAULTS);
bs.on('data', function (data) { });
bs.once('end', function() { console.timeEnd('test'); });
const str = 'X'.repeat(16 * 1024);
console.time('test');
for(var i = 0;i<10000;i++) { bs.write(str); }
bs.end();
```
And got for the proposed 

> test: 778.057ms

and current implementation

> test: 1368.844ms

**Comment by braydonf** [comment]
Nice.

I think there is also performance tests in https://github.com/Storj/kfs/tree/master/perf

**Comment by 161chihuahuas** [comment]
That's a pretty significant performance improvement. I'd like to see updated graphs generated from the performance tests if @pgerbes has time to pull this an run them.

**Comment by littleskunk** [comment]
I will install the pull request on my farmer to test the memory usage. That will take a few days.

**Comment by vasilenkoalexey** [comment]
littleskunk, I need 2-3 days to implement another improvements. Could you wait pls?

**Comment by vasilenkoalexey** [comment]
Now it's finished

**Comment by braydonf** [comment]
Found something interesting while testing. I can run `cd perf && node --inspect index.js exec` on this branch and record an allocation profile, however it segfaults when trying to do that on the master branch.

**Comment by braydonf** [comment]
Results from running perf/index: https://gist.github.com/braydonf/5674f5288cb543d0cea2c1bbcbcda250

**Comment by vasilenkoalexey** [comment]
Maybe there are some local problems? On my PC, `node --inspect index.js exec` was successful.

**Comment by littleskunk** [comment]
I installed the pull request on my farmer.
```
    └── kfs@3.1.5(git://github.com/vasilenkoalexey/kfs.git#fb5c420025462f8c8fb547be506ea563a8be61b0)
```

I don't see any difference. Same memory and CPU usage as master branch. Nothing I could measure.

**Comment by littleskunk** [comment]
It is working. I was lucky today. A renter is uploading 25GB shards to me. The old implementation needs 500MB memory for one single 25GB transfer. I installed this pull request and again one single 25GB transfer but this time only 200-300MB memory usage.

Please merge and publish.

**Pull request merged**
